# Generated by Django 3.2 on 2021-04-28 10:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('investment', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=244)),
                ('icon', models.ImageField(upload_to='')),
                ('price', models.FloatField()),
                ('is_public', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Investment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purchased_price', models.FloatField(default=0)),
                ('purchased_quantity', models.FloatField(default=0)),
                ('purchased_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='investment.asset')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='InvestmentOrders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.FloatField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('is_completed', models.BooleanField()),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='investment.asset')),
                ('investment', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='investment.investment')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MarketListing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_type', models.CharField(choices=[('BUY', 'BUY'), ('SELL', 'SELL')], max_length=10)),
                ('traded_coins', models.FloatField(default=0)),
                ('remaining_coins', models.FloatField(default=0)),
                ('partial_binding', models.BooleanField(default=False)),
                ('accepts_coin_trading', models.BooleanField(default=False)),
                ('accepts_money_transaction', models.BooleanField(default=False)),
                ('has_stop_condition', models.BooleanField(default=False)),
                ('expiry', models.DateTimeField()),
                ('has_stop_loss_range', models.BooleanField(default=False)),
                ('stop_loss_high', models.FloatField()),
                ('stop_loss_low', models.FloatField()),
                ('accepted_coins', models.ManyToManyField(related_name='accepted_coins', to='investment.Asset')),
                ('assets_to_trade', models.ManyToManyField(related_name='assets_to_trade', to='investment.Asset')),
            ],
        ),
        migrations.DeleteModel(
            name='Assets',
        ),
        migrations.AlterField(
            model_name='wallet',
            name='owner',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
