# Generated by Django 3.2 on 2021-04-27 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investment', '0002_alter_wallet_owner'),
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=244)),
                ('icon', models.ImageField(upload_to='')),
                ('price', models.FloatField()),
                ('is_public', models.BooleanField(default=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Assets',
        ),
    ]
