# Generated by Django 3.2 on 2021-04-28 12:14

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('investment', '0002_auto_20210428_1005'),
    ]

    operations = [
        migrations.AddField(
            model_name='marketlisting',
            name='posted_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
