# Generated by Django 3.2 on 2021-04-27 17:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('investment', '0004_investment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='investment',
            name='purchased_price',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='investment',
            name='purchased_quantity',
            field=models.FloatField(default=0),
        ),
        migrations.CreateModel(
            name='InvestmentOrders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.FloatField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('is_completed', models.BooleanField()),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='investment.asset')),
                ('investment', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='investment.investment')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
